apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{Deployment}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{Deployment}#
  template:
    metadata:
      labels:
        app: #{Deployment}#
        type: #{Deployment}#
    spec:
      containers:
        - name: #{Deployment}#
          image: iboslimitedbd/#{DockerImage}#:#{Build.BuildId}#
          # resources:
          #   limits:
          #     memory: "3024Mi"
          #     cpu: "900m"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockercred

---
apiVersion: v1
kind: Service
metadata:
  name: #{Deployment}#
spec:
  selector:
    app: #{Deployment}#
  ports:
    - port: 80
      targetPort: 80
  # type: LoadBalancer
  # loadBalancerIP: 172.18.18.56
