export const column = {
  sl: "SL",
  strWorkPlaceGroupName: "Workplace Group",
  strWorkPlaceName: "Workplace",
  strDepartmentName: "Department",
  strSectionName: "Section",
  EmployeeCode: "Employee Id",
  strEmployeeName: "Employee Name",
  strDesignation: "Designation",
  strLeaveTypeName: "Leave Type",
  Location: "Location",
  StartDate: "From Date",
  StartTime: "Start Time",
  EndDate: "To Date",
  EndTime: "End Time",
  HalfDayHours: "Half Day Hours",
  TotalDays: "Days",
  ApplicationDate: "Application Date",
};
