export const column = {
  sl: "SL",
  StrWorkPlaceGroupName: "Workplace Group",
  StrWorkPlaceName: "Workplace",
  StrDepartmentName: "Department",
  StrSectionName: "Section",
  StrEmployeeCode: "Employee Id",
  StrEmployeeName: "Employee Name",
  StrDesignation: "Designation",
  StrSupersvisorName: "Supersvisor",
  StrLeaveTypeName: "Leave Type",
  StrAddressDuetoLeave: "Location",
  StartDate: "From Date",
  StartEndTime: "Duration",
  EndDate: "To Date",
  HalfDayHours: "Half Day Hours",
  TotalDays: "Days",
  ApplicationDate: "Application Date",
  TotalApprover: "Total Approver",
  ApprovedApplications: "Approved Application",
  PendingApplications: "Pending Application"
};
