export const landingData = {
  currentPage: 1,
  data: [
    {
      sl: 1,
      jobName: "Senior Interaction Designer",
      jobLocation: "Dhaka, Bangladesh",
      totalCadidate: 10983458,
      newCadidate: 25,
      jobReqAssignee: "Adams Baker",
      jobAssignee: "Shakil Imtiaz (HR)",
      jobPublish: "23, April, 2021",
      jobOpening: "Remaining 10 days",
      jobStatus: "Open",
      jobStatusTag: "not started",
    },
    {
      sl: 2,
      jobName: "Expert DevOps",
      jobLocation: "Dhaka, Bangladesh",
      totalCadidate: 10983458,
      newCadidate: 25,
      jobReqAssignee: "Adams Baker",
      jobAssignee: "Shakil Imtiaz (HR)",
      jobPublish: "23, April, 2021",
      jobOpening: "Remaining 10 days",
      jobStatus: "completed",
      jobStatusTag: "completed",
    },
    {
      sl: 3,
      jobName: "Software Quality Assurance",
      jobLocation: "Dhaka, Bangladesh",
      totalCadidate: 10983458,
      newCadidate: 25,
      jobReqAssignee: "Adams Baker",
      jobAssignee: "Shakil Imtiaz (HR)",
      jobPublish: "23, April, 2021",
      jobOpening: "Remaining 10 days",
      jobStatus: "Closed",
      jobStatusTag: "on hold",
    },
    {
      sl: 4,
      jobName: "Lead UX Designer",
      jobLocation: "Dhaka, Bangladesh",
      totalCadidate: 10983458,
      newCadidate: 25,
      jobReqAssignee: "Adams Baker",
      jobAssignee: "Shakil Imtiaz (HR)",
      jobPublish: "23, April, 2021",
      jobOpening: "Remaining 10 days",
      jobStatus: "Expired",
      jobStatusTag: "in progress",
    },
  ],
  pageSize: 5,
  totalCount: 100,
};
