export const column = {
  sl: "SL",
  StrWorkPlaceGroupName: "Workplace Group",
  StrWorkPlaceName: "Workplace",
  StrDepartmentName: "Department",
  StrSectionName: "Section",
  StrEmployeeCode: "Employee Id",
  StrEmployeeName: "Employee Name",
  StrDesignation: "Designation",
  StrSupersvisorName: "Supersvisor",
  StrLineManagerName: "Line Manager",
  StrDottedSupersvisorName: "Dotted Supersvisor",
  // StrCalendarName: "Calendar",
  TotalNightShiftCount: "Total Night Shift",
};
