import {
  SettingsOutlined,
  DashboardOutlined,
  PeopleAltOutlined,
  VerifiedUserOutlined,
  AccountBoxOutlined,
  EmojiEventsOutlined,
  BarChartOutlined,
} from "@mui/icons-material";

const menuList = [
  {
    id: 1,
    icon: <DashboardOutlined sx={{ marginRight: "8px", fontSize: "18px" }} />,
    label: "Overview",
    to: "/",
    isFirstLabel: false,
    subs: [],
  },
  // {
  //   id: 2,
  //   icon: <DashboardOutlined sx={{ marginRight: "8px", fontSize: "18px" }} />,
  //   label: "Recruitment",
  //   to: "/",
  //   isFirstLabel: false,
  //   subs: [],
  // },
  {
    id: 3,
    icon: <PeopleAltOutlined sx={{ marginRight: "8px", fontSize: "18px" }} />,
    label: "Employee Management",
    to: "/employee-profile",
    isFirstLabel: true,
    subs: [
      {
        secondLabelId: 1,
        label: "Employee",
        to: "/employee-profile/employee",
        isSecondLabel: false,
        nestedSubs: [],
      },
      // {
      //   secondLabelId: 2,
      //   label: "Training and Development",
      //   to: "/employee-profile/trainingAndDevelopment",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      // {
      //   secondLabelId: 3,
      //   label: "Reward & Punishment",
      //   to: "/employee-profile/rewardAndPunishment",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      {
        secondLabelId: 4,
        label: "Confirmation",
        to: "/employee-profile/confirmation",
        isSecondLabel: false,
        nestedSubs: [],
      },
      {
        secondLabelId: 5,
        label: "Rewards & Punishment",
        to: "/employee-profile/rewardsandpunishment",

        isSecondLabel: false,
        nestedSubs: [],
      },
      {
        secondLabelId: 5,
        label: "Attendence Adjust",
        to: "/employee-profile/attendenceAdjust",
        isSecondLabel: false,
        nestedSubs: [],
      },
      {
        secondLabelId: 6,
        label: "Overtime Entry",
        to: "/employee-profile/overTimeEntry",
        isSecondLabel: false,
        nestedSubs: [],
      },
      {
        secondLabelId: 7,
        label: "Leave Application",
        to: "/employee-profile/leaveApplication",
        isSecondLabel: false,
        nestedSubs: [],
      },
      {
        secondLabelId: 8,
        label: "Movement Application",
        to: "/employee-profile/movementApplication",
        isSecondLabel: false,
        nestedSubs: [],
      },
      {
        secondLabelId: 9,
        label: "Loan Request",
        to: "/employee-profile/loanRequest",
        isSecondLabel: false,
        nestedSubs: [],
      },
      {
        secondLabelId: 10,
        label: "Separation",
        to: "/employee-profile/separation",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Application",
            to: "/employee-profile/separation/application",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Report",
            to: "/employee-profile/separation/report",
            isThirdLabel: false,
          },
        ],
      },
      {
        secondLabelId: 10,
        label: "Reports",
        to: "/employee-profile/reports",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Attendance Report",
            to: "/employee-profile/reports/attendanceReport",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Roster Report",
            to: "/employee-profile/reports/rosterReport",
            isThirdLabel: false,
          },
          {
            id: 4,
            label: "Roster Details",
            to: "/employee-profile/reports/rosterDetails",
            isThirdLabel: false,
          },
          {
            id: 5,
            label: "Attendance By Roster",
            to: "/employee-profile/reports/attendanceByRoster",
            isThirdLabel: false,
          },
          {
            id: 6,
            label: "Loan History",
            to: "/employee-profile/reports/loanHistory",
            isThirdLabel: false,
          },
          {
            id: 7,
            label: "Leave History",
            to: "/employee-profile/reports/leaveHistory",
            isThirdLabel: false,
          },
          {
            id: 8,
            label: "Movement History",
            to: "/employee-profile/reports/movementHistory",
            isThirdLabel: false,
          },
          {
            id: 9,
            label: "OverTime Report",
            to: "/employee-profile/reports/overTimeReport",
            isThirdLabel: false,
          },
        ],
      },
    ],
  },

  {
    id: 4,
    icon: <SettingsOutlined sx={{ marginRight: "8px", fontSize: "18px" }} />,
    label: "Administration",
    to: "/administration",
    isFirstLabel: true,
    subs: [
      {
        secondLabelId: 1,
        label: "Role Management",
        to: "/administration/roleManagement",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 2,
            label: "Users Info",
            to: "/administration/roleManagement/usersInfo",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "User Group",
            to: "/administration/roleManagement/userGroup",
            isThirdLabel: false,
          },
          {
            secondLabelId: 13,
            label: "Feature Group",
            to: "/administration/roleManagement/featureGroup",
            isThirdLabel: false,
          },
          {
            secondLabelId: 14,
            label: "User Role Extension",
            to: "/administration/roleManagement/userRoleExtension",
            isThirdLabel: false,
          },
          {
            secondLabelId: 13,
            label: "User Role Manager",
            to: "/administration/roleManagement/userRoleManager",
            isThirdLabel: false,
          },
        ],
      },
      {
        secondLabelId: 2,
        label: "Leave and Movement",
        to: "/administration/leaveandmovement",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 2,
            label: "Leave Type",
            to: "/administration/leaveandmovement/leavePolicy",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Movement Type",
            to: "/administration/leaveandmovement/movementPolicy",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Approval Pipeline",
            to: "/administration/leaveandmovement/approvalPipeline",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Leave Policy",
            to: "/administration/leaveandmovement/yearlyLeavePolicy",
            isThirdLabel: false,
          },
        ],
      },

      // {
      //   secondLabelId: 3,
      //   label: "Payroll Process",
      //   to: "/administration/payrollProcess",
      //   isSecondLabel: true,
      //   nestedSubs: [
      //     {
      //       id: 1,
      //       label: "Generate Payroll",
      //       to: "/administration/payrollProcess/generatePayroll",
      //       isThirdLabel: false,
      //     },
      //     {
      //       id: 2,
      //       label: "Adjust Payroll",
      //       to: "/administration/payrollProcess/adjustPayroll",
      //       isThirdLabel: false,
      //     },
      //   ],
      // },
      {
        secondLabelId: 3,
        label: "Time Management",
        to: "/administration/timeManagement",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Holiday Setup",
            to: "/administration/timeManagement/holidaySetup",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Calendar Setup",
            to: "/administration/timeManagement/calendarSetup",
            isThirdLabel: false,
          },
          {
            id: 3,
            label: "Exception Offday",
            to: "/administration/timeManagement/exceptionOffDay",
            isThirdLabel: false,
          },
          {
            id: 4,
            label: "Roster Setup",
            to: "/administration/timeManagement/rosterSetup",
            isThirdLabel: false,
          },
          {
            id: 5,
            label: "Holiday & Exception Offday Assign",
            to: "/administration/timeManagement/holidayAndExceptionOffdayAssign",
            isThirdLabel: false,
          },
          {
            id: 6,
            label: "Calendar Assign",
            to: "/administration/timeManagement/calendarAssign",
            isThirdLabel: false,
          },
          {
            id: 7,
            label: "Offday Assign",
            to: "/administration/timeManagement/offDayAssign",
            isThirdLabel: false,
          },
          {
            id: 8,
            label: "Location Assign",
            to: "/administration/timeManagement/locationAssign",
            isThirdLabel: false,
          },
          {
            id: 9,
            label: "Extra Side Duty",
            to: "/administration/timeManagement/outsideDuty",
            isThirdLabel: false,
          },
        ],
      },
      // {
      //   secondLabelId: 4,
      //   label: "Leave & Movement policy",
      //   to: "/administration/leaveMovementPolicy",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      // {
      //   secondLabelId: 5,
      //   label: "Planning & budgeting",
      //   to: "/administration/planningAndBudgeting",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      // {
      //   secondLabelId: 6,
      //   label: "Loan Management",
      //   to: "/administration/loanManagement",
      //   isSecondLabel: true,
      //   nestedSubs: [
      //     {
      //       id: 1,
      //       label: "Loan Type",
      //       to: "/administration/loanManagement/loanType",
      //       isThirdLabel: false,
      //     },
      //   ],
      // },
      // {
      //   secondLabelId: 7,
      //   label: "Transport Scheduling",
      //   to: "/administration/transportScheduling",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      // {
      //   secondLabelId: 8,
      //   label: "Asset Create",
      //   to: "/administration/assetCreate",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      // {
      //   secondLabelId: 9,
      //   label: "Cafeteria Management",
      //   to: "/administration/cafeteriaManagement",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      //   secondLabelId: 10,
      //   label: "Charity",
      //   to: "/administration/charity",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      {
        secondLabelId: 11,
        icon: (
          <SettingsOutlined sx={{ marginRight: "8px", fontSize: "18px" }} />
        ),
        label: "Control Panel",
        to: "/administration/configuration",
        isSecondLabel: true,
        nestedSubs: [
          {
            secondLabelId: 1,
            label: "Business Unit",
            to: "/administration/configuration/business-unit",
            isSecondLabel: false,
            nestedSubs: [],
          },
          {
            secondLabelId: 2,
            label: "SBU",
            to: "/administration/configuration/sbu",
            isSecondLabel: false,
            nestedSubs: [],
          },
          {
            secondLabelId: 3,
            label: "Department",
            to: "/administration/configuration/department",
            isSecondLabel: false,
            nestedSubs: [],
          },
          {
            secondLabelId: 4,
            label: "HR Position",
            to: "/administration/configuration/hr-position",
            isSecondLabel: false,
            nestedSubs: [],
          },
          {
            secondLabelId: 5,
            label: "Designation",
            to: "/administration/configuration/designation",
            isSecondLabel: false,
            nestedSubs: [],
          },
          {
            secondLabelId: 6,
            label: "Workplace",
            to: "/administration/configuration/workplace",
            isSecondLabel: false,
            nestedSubs: [],
          },
          {
            secondLabelId: 7,
            label: "Document Type",
            to: "/administration/configuration/document-type",
            isSecondLabel: false,
            nestedSubs: [],
          },
          {
            secondLabelId: 8,
            label: "Religion",
            to: "/administration/configuration/religion",
            isSecondLabel: false,
            nestedSubs: [],
          },
          {
            secondLabelId: 8,
            label: "Organogram",
            to: "/administration/configuration/organogram",
            isSecondLabel: false,
            nestedSubs: [],
          },
        ],
      },
      {
        secondLabelId: 6,
        label: "Asset Management",
        to: "/administration/assetManagement",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 2,
            label: "Registration",
            to: "/administration/assetManagement/registration",
            isThirdLabel: false,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    icon: (
      <VerifiedUserOutlined sx={{ marginRight: "8px", fontSize: "18px" }} />
    ),
    label: "Approval",
    to: "/approval",
    isFirstLabel: false,
    subs: [],
  },

  {
    id: 6,
    icon: <AccountBoxOutlined sx={{ marginRight: "8px", fontSize: "18px" }} />,
    label: "Employee Self Service",
    to: "/employeeSelfService",
    isFirstLabel: true,
    subs: [
      {
        secondLabelId: 1,
        label: "About Me",
        to: "/employeeSelfService/aboutMe",
        isSecondLabel: false,
        nestedSubs: [],
      },
      {
        secondLabelId: 1,
        label: "My Rewards & Punishment",
        to: "/employeeSelfService/myrewardsandpunishment",
        isSecondLabel: false,
        nestedSubs: [],
      },
      {
        secondLabelId: 2,
        label: "Time Management",
        to: "/employeeSelfService/timeManagement",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Attendence Adjust",
            to: "/employeeSelfService/timeManagement/attendenceAdjust",
            isThirdLabel: false,
          },
          {
            id: 1,
            label: "Attendence Adjust Req.",
            to: "/employeeSelfService/timeManagement/attendenceAdjustRequest",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Overtime Entry",
            to: "/employeeSelfService/timeManagement/overTimeEntry",
            isThirdLabel: false,
          },
          // {
          //   id: 3,
          //   label: "Overtime Requisition",
          //   to: "/employeeSelfService/timeManagement/overTimeRequisition",
          //   isThirdLabel: false,
          // },
        ],
      },
      {
        secondLabelId: 3,
        label: "Leave and Movement",
        to: "/employeeSelfService/leaveAndMovement",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Leave Application",
            to: "/employeeSelfService/leaveAndMovement/leaveApplication",
            isThirdLabel: false,
          },
          {
            id: 3,
            label: "Movement Application",
            to: "/employeeSelfService/leaveAndMovement/movementApplication",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Leave Encashment",
            to: "/employeeSelfService/leaveAndMovement/leaveEncashment",
            isThirdLabel: false,
          },
        ],
      },
      // {
      //   secondLabelId: 4,
      //   label: "Task Management",
      //   to: "/employeeSelfService/taskManagement",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      // {
      //   secondLabelId: 5,
      //   label: "Meeting",
      //   to: "/employeeSelfService/meeting",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      {
        secondLabelId: 4,
        label: "Loan & Financial Aid",
        to: "/employeeSelfService/loanFinancialAid",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Loan Request",
            to: "/employeeSelfService/loanFinancialAid/loanRequest",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Loan Reschedule",
            to: "/employeeSelfService/loanFinancialAid/loanReschedule",
            isThirdLabel: false,
          },
        ],
      },
      {
        secondLabelId: 5,
        label: "Expense",
        to: "/employeeSelfService/expense",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Expense Application",
            to: "/employeeSelfService/expense/expenseApplication",
            isThirdLabel: false,
          },
        ],
      },
      // {
      //   secondLabelId: 6,
      //   label: "Approval",
      //   to: "/employeeSelfService",
      //   isSecondLabel: true,
      //   nestedSubs: [
      //     {
      //       id: 1,
      //       label: "Leave Approval",
      //       to: "/employeeSelfService/approval/leaveApproval",
      //       isThirdLabel: false,
      //     },
      //     {
      //       id: 2,
      //       label: "Leave Encashment Approval",
      //       to: "/employeeSelfService/approval/leaveEncashmentApproval",
      //       isThirdLabel: false,
      //     },
      //     {
      //       id: 3,
      //       label: "Movement Approval",
      //       to: "/employeeSelfService/approval/movementApproval",
      //       isThirdLabel: false,
      //     },
      //     {
      //       id: 4,
      //       label: "Attendance Approval",
      //       to: "/employeeSelfService/approval/attendanceApproval",
      //       isThirdLabel: false,
      //     },
      //     {
      //       id: 5,
      //       label: "Overtime Approval",
      //       to: "/employeeSelfService/approval/overtimeApproval",
      //       isThirdLabel: false,
      //     },
      //     {
      //       id: 5,
      //       label: "Salary Approval",
      //       to: "/employeeSelfService/approval/salaryApproval",
      //       isThirdLabel: false,
      //     },
      //     {
      //       id: 6,
      //       label: "Loan Approval",
      //       to: "/employeeSelfService/approval/loanApproval",
      //       isThirdLabel: false,
      //     },
      //     // {
      //     //   id: 4,
      //     //   label: "Transfer Approval",
      //     //   to: "/employeeSelfService/approval/transferApproval",
      //     //   isThirdLabel: false,
      //     // },
      //     {
      //       id: 7,
      //       label: "Separation Approval",
      //       to: "/employeeSelfService/approval/separationApproval",
      //       isThirdLabel: false,
      //     },
      //   ],
      // },
      // {
      //   secondLabelId: 7,
      //   label: "Expense & Advance",
      //   to: "/employeeSelfService/expenseAndAdvanced",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },

      // {
      //   secondLabelId: 9,
      //   label: "Transport Management",
      //   to: "/employeeSelfService/transportManagement",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      // {
      //   secondLabelId: 10,
      //   label: "Asset Request",
      //   to: "/employeeSelfService/assetRequest",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      // {
      //   secondLabelId: 11,
      //   label: "Cafetaria Management",
      //   to: "/employeeSelfService/cafetariaManagement",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      {
        secondLabelId: 6,
        label: "Report",
        to: "/employeeSelfService/report",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 11,
            label: "Daily Attendance",
            to: "/employeeSelfService/report/dailyAttendance",
            isThirdLabel: false,
          },
          // {
          //   id: 1,
          //   label: "Attendance Report",
          //   to: "/employeeSelfService/report/attendanceReport",
          //   isThirdLabel: false,
          // },
          {
            id: 2,
            label: "Job Card",
            to: "/employeeSelfService/report/attendanceDetails",
            isThirdLabel: false,
          },
          // 3,4,5 no item move to EM menulist
          // {
          //   id: 6,
          //   label: "Asset Register",
          //   to: "/employeeSelfService/report/assetRegister",
          //   isThirdLabel: false,
          // },
          {
            id: 7,
            label: "Loan History",
            to: "/employeeSelfService/report/loanHistory",
            isThirdLabel: false,
          },
          {
            id: 8,
            label: "Leave History",
            to: "/employeeSelfService/report/leaveHistory",
            isThirdLabel: false,
          },
          {
            id: 9,
            label: "Movement History",
            to: "/employeeSelfService/report/movementHistory",
            isThirdLabel: false,
          },
          {
            id: 10,
            label: "OverTime Report",
            to: "/employeeSelfService/report/overTimeReport",
            isThirdLabel: false,
          },
          {
            id: 12,
            label: "Expense Report",
            to: "/employeeSelfService/report/expenseReport",
            isThirdLabel: false,
          },
          {
            id: 13,
            label: "Asset Details",
            to: "/employeeSelfService/report/assetDetails",
            isThirdLabel: false,
          },
        ],
      },
      {
        secondLabelId: 7,
        label: "Contact Book",
        to: "/employeeSelfService/contactBook",
        isSecondLabel: false,
        nestedSubs: [],
      },
      {
        secondLabelId: 8,
        label: "Asset Management",
        to: "/employeeSelfService/assetManagement",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Assign",
            to: "/employeeSelfService/assetManagement/assign",
            isThirdLabel: false,
          },
        ],
      },
    ],
  },
  {
    id: 7,
    icon: <EmojiEventsOutlined sx={{ marginRight: "8px", fontSize: "18px" }} />,
    label: "Compensation & Benefits",
    to: "/compensationAndBenefits",
    isFirstLabel: true,
    subs: [
      {
        secondLabelId: 1,
        label: "Configuration",
        to: "/compensationAndBenefits/configuration",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Payroll Element & Rule",
            to: "/compensationAndBenefits/configuration/payrollElementAndRule",
            isThirdLabel: false,
          },
          {
            id: 1,
            label: "Bonus Setup",
            to: "/compensationAndBenefits/configuration/bonusSetup",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Paryroll Group",
            to: "/compensationAndBenefits/configuration/payrollGroup",
            isThirdLabel: false,
          },
          {
            id: 3,
            label: "Grade",
            to: "/compensationAndBenefits/configuration/grade",
            isThirdLabel: false,
          },
          {
            id: 4,
            label: "Pay Frequency",
            to: "/compensationAndBenefits/configuration/payFrequency",
            isThirdLabel: false,
          },
        ],
      },
      {
        secondLabelId: 2,
        label: "Employee Salary",
        to: "/compensationAndBenefits/employeeSalary",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Salary Assign",
            to: "/compensationAndBenefits/employeeSalary/salaryAssign",
            isThirdLabel: false,
          },
          // {
          //   id: 2,
          //   label: "Generate Salary",
          //   to: "/compensationAndBenefits/employeeSalary/salaryGenerate",
          //   isThirdLabel: false,
          // },
          // {
          //   id: 3,
          //   label: "Bulk Increment",
          //   to: "/compensationAndBenefits/employeeSalary/bulkIncrement",
          //   isThirdLabel: false,
          // },
        ],
      },
      {
        secondLabelId: 3,
        label: "Payroll Process",
        to: "/compensationAndBenefits/payrollProcess",
        isSecondLabel: true,
        nestedSubs: [
          // {
          //   id: 1,
          //   label: "Bonus Setup",
          //   to: "/compensationAndBenefits/payrollProcess/bonusSetup",
          //   isThirdLabel: false,
          // },
          {
            id: 2,
            label: "Generate Salary",
            to: "/compensationAndBenefits/payrollProcess/generateSalary",
            isThirdLabel: false,
          },
          {
            id: 4,
            label: "Generate Bonus",
            to: "/compensationAndBenefits/payrollProcess/bonusGenerate",
            isThirdLabel: false,
          },
        ],
      },
      // {
      //   secondLabelId: 4,
      //   label: "Approval",
      //   to: "/compensationAndBenefits/approval",
      //   isSecondLabel: true,
      //   nestedSubs: [
      //     {
      //       id: 1,
      //       label: "Salary Approval",
      //       to: "/compensationAndBenefits/approval/salaryApproval",
      //       isThirdLabel: false,
      //     },
      //     {
      //       id: 2,
      //       label: "Bonus Approval",
      //       to: "/compensationAndBenefits/approval/bonusApproval",
      //       isThirdLabel: false,
      //     },
      //   ],
      // },
      // {
      //   secondLabelId: 4,
      //   label: "Group Insurance",
      //   to: "/compensationAndBenefits/groupInsurance",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      // {
      //   secondLabelId: 5,
      //   label: "PF And Gratutity",
      //   to: "/compensationAndBenefits/PFAndGratutity",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      // {
      //   secondLabelId: 6,
      //   label: "Tax",
      //   to: "/compensationAndBenefits/tax",
      //   isSecondLabel: true,
      //   nestedSubs: [
      //     {
      //       id: 1,
      //       label: "Eligible Employee List",
      //       to: "/compensationAndBenefits/tax/eligibleEmployeeList",
      //       isThirdLabel: false,
      //     },
      //     {
      //       id: 2,
      //       label: "Provision Amount Calculation",
      //       to: "/compensationAndBenefits/tax/provisionAmountCalculation",
      //       isThirdLabel: false,
      //     },
      //     {
      //       id: 3,
      //       label: "Tax Deduction",
      //       to: "/compensationAndBenefits/tax/taxDeduction",
      //       isThirdLabel: false,
      //     },
      //     {
      //       id: 4,
      //       label: "Tax Calculation",
      //       to: "/compensationAndBenefits/tax/taxCalculation",
      //       isThirdLabel: false,
      //     },
      //   ],
      // },
      // {
      //   secondLabelId: 7,
      //   label: "Promotion",
      //   to: "/compensationAndBenefits/promotion",
      //   isSecondLabel: true,
      //   nestedSubs: [
      //     {
      //       id: 1,
      //       label: "Promotion Entry",
      //       to: "/compensationAndBenefits/promotion/promotionEntry",
      //       isThirdLabel: false,
      //     },
      //   ],
      // },
      // {
      //   secondLabelId: 8,
      //   label: "Asset Management",
      //   to: "/compensationAndBenefits/assetManagement",
      //   isSecondLabel: false,
      //   nestedSubs: [],
      // },
      {
        secondLabelId: 9,
        label: "Reports",
        to: "/compensationAndBenefits/reports",
        isSecondLabel: true,
        nestedSubs: [
          // {
          //   id: 1,
          //   label: "PF Ledger",
          //   to: "/compensationAndBenefits/reports/PFLedger",
          //   isThirdLabel: false,
          // },
          {
            id: 2,
            label: "Salary Details & Payslip",
            to: "/compensationAndBenefits/reports/salaryPaySlip",
            isThirdLabel: false,
          },
          {
            id: 3,
            label: "Department wise Salary",
            to: "/compensationAndBenefits/reports/departmentWiseSalary",
            isThirdLabel: false,
          },
          // {
          //   id: 3,
          //   label: "Bank Advice",
          //   to: "/compensationAndBenefits/reports/bankAdvice",
          //   isThirdLabel: false,
          // },
          // {
          //   id: 4,
          //   label: "Comparative Analysis",
          //   to: "/compensationAndBenefits/reports/comparativeAnalysis",
          //   isThirdLabel: false,
          // },
          // {
          //   id: 5,
          //   label: "Variance Report",
          //   to: "/compensationAndBenefits/reports/varianceReport",
          //   isThirdLabel: false,
          // },
          // {
          //   id: 6,
          //   label: "Cash Disbursement Register",
          //   to: "/compensationAndBenefits/reports/cashDisbursementRegister",
          //   isThirdLabel: false,
          // },
          // {
          //   id: 7,
          //   label: "Tax Slip",
          //   to: "/compensationAndBenefits/reports/taxSlip",
          //   isThirdLabel: false,
          // },
        ],
      },
    ],
  },
  // {
  //   id: 8,
  //   icon: <PersonOutlineOutlined sx={{ marginRight: "8px", fontSize: "18px" }} />,
  //   label: "Performance Management System",
  //   to: "/performanceManagementSystem",
  //   isFirstLabel: true,
  //   subs: [],
  // },
  {
    id: 9,
    icon: <BarChartOutlined sx={{ marginRight: "8px", fontSize: "18px" }} />,
    label: "Analytics",
    to: "/analytics",
    isFirstLabel: true,
    subs: [
      {
        secondLabelId: 1,
        label: "Salary Comparative Analysis",
        to: "/analytics/comparativeAnalysis",
        isSecondLabel: false,
        nestedSubs: [],
      },
      {
        secondLabelId: 1,
        label: "CTC",
        to: "/analytics/ctc",
        isSecondLabel: false,
        nestedSubs: [],
      },
    ],
  },
];

const menuListForEmp = [
  {
    id: 6,
    icon: <AccountBoxOutlined sx={{ marginRight: "8px", fontSize: "18px" }} />,
    label: "Employee Self Service",
    to: "/employeeSelfService",
    isFirstLabel: true,
    subs: [
      {
        secondLabelId: 1,
        label: "About Me",
        to: "/employeeSelfService/aboutMe",
        isSecondLabel: false,
        nestedSubs: [],
      },
      {
        secondLabelId: 1,
        label: "My Rewards & Punishment",
        to: "/employeeSelfService/myrewardsandpunishment",
        isSecondLabel: false,
        nestedSubs: [],
      },
      {
        secondLabelId: 2,
        label: "Time Management",
        to: "/employeeSelfService/timeManagement",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Attendence Adjust Req.",
            to: "/employeeSelfService/timeManagement/attendenceAdjustRequest",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Overtime Entry",
            to: "/employeeSelfService/timeManagement/overTimeEntry",
            isThirdLabel: false,
          },
        ],
      },
      {
        secondLabelId: 3,
        label: "Leave and Movement",
        to: "/employeeSelfService/leaveAndMovement",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Leave Application",
            to: "/employeeSelfService/leaveAndMovement/leaveApplication",
            isThirdLabel: false,
          },
          {
            id: 3,
            label: "Movement Application",
            to: "/employeeSelfService/leaveAndMovement/movementApplication",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Leave Encashment",
            to: "/employeeSelfService/leaveAndMovement/leaveEncashment",
            isThirdLabel: false,
          },
        ],
      },
      {
        secondLabelId: 4,
        label: "Loan & Financial Aid",
        to: "/employeeSelfService/loanFinancialAid",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Loan Request",
            to: "/employeeSelfService/loanFinancialAid/loanRequest",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Loan Reschedule",
            to: "/employeeSelfService/loanFinancialAid/loanReschedule",
            isThirdLabel: false,
          },
        ],
      },
      {
        secondLabelId: 5,
        label: "Expense",
        to: "/employeeSelfService/expense",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 1,
            label: "Expense Application",
            to: "/employeeSelfService/expense/expenseApplication",
            isThirdLabel: false,
          },
        ],
      },
      {
        secondLabelId: 6,
        label: "Report",
        to: "/employeeSelfService/report",
        isSecondLabel: true,
        nestedSubs: [
          {
            id: 11,
            label: "Daily Attendance",
            to: "/employeeSelfService/report/dailyAttendance",
            isThirdLabel: false,
          },
          {
            id: 1,
            label: "Attendance Report",
            to: "/employeeSelfService/report/attendanceReport",
            isThirdLabel: false,
          },
          {
            id: 2,
            label: "Job Card",
            to: "/employeeSelfService/report/attendanceDetails",
            isThirdLabel: false,
          },
          {
            id: 3,
            label: "Roster Report",
            to: "/employeeSelfService/report/rosterReport",
            isThirdLabel: false,
          },
          {
            id: 4,
            label: "Roster Details",
            to: "/employeeSelfService/report/rosterDetails",
            isThirdLabel: false,
          },
          {
            id: 5,
            label: "Attendance By Roster",
            to: "/employeeSelfService/report/attendanceByRoster",
            isThirdLabel: false,
          },
          {
            id: 7,
            label: "Loan History",
            to: "/employeeSelfService/report/loanHistory",
            isThirdLabel: false,
          },
          {
            id: 8,
            label: "Leave History",
            to: "/employeeSelfService/report/leaveHistory",
            isThirdLabel: false,
          },
          {
            id: 9,
            label: "Movement History",
            to: "/employeeSelfService/report/movementHistory",
            isThirdLabel: false,
          },
          {
            id: 10,
            label: "OverTime Report",
            to: "/employeeSelfService/report/overTimeReport",
            isThirdLabel: false,
          },
          {
            id: 12,
            label: "Expense Report",
            to: "/employeeSelfService/report/expenseReport",
            isThirdLabel: false,
          },
          {
            id: 13,
            label: "Asset Details",
            to: "/employeeSelfService/report/assetDetails",
            isThirdLabel: false,
          },
        ],
      },
    ],
  },
];

export { menuList, menuListForEmp };
