export const landingData = {
  currentPage: 1,
  data: [
    {
      sl: 1,
      userId: 10405,
      code: "User-1-521-001",
      userName: "Mahmud",
      email: "demo@gmail.com",
      ratings: 1,
      status: "Hire",
      performance: 8.6,
      isActive: true,
      comment: "User-1 Comment",
      isStatusShown: true,
      isChecked: false,
    },
    {
      sl: 2,
      userId: 10406,
      code: "User-2-242-001",
      userName: "Jubayer",
      email: "demo@gmail.com",
      ratings: 2,
      performance: 58.8,
      status: "Short List",
      isActive: false,
      comment: "User-2 Comment",
      isStatusShown: true,
      isChecked: false,
    },
    {
      sl: 3,
      userId: 10409,
      code: "User-3-807-001",
      userName: "Mahmud",
      email: "demo@gmail.com",
      ratings: 3,
      performance: 88.4,
      status: "Written",
      isActive: true,
      comment: "User-3",
      isChecked: false,
      isStatusShown: true,
    },
    {
      sl: 4,
      userId: 10410,
      code: "User-4-249-001",
      userName: "Bulbul Ahmed",
      email: "demo@gmail.com",
      ratings: 4,
      performance: 12.3,
      isActive: false,
      comment: "User-4 Comment",
      isStatusShown: true,
      status: "Reject",
      isChecked: false,
    },
    {
      sl: 5,
      userId: 10411,
      code: "User-6-558-001",
      userName: "User-5",
      email: "demo@gmail.com",
      ratings: 5,
      performance: 45.1,
      isActive: true,
      comment: "User-5 Comment",
      isStatusShown: true,
      status: "Reject",
      isChecked: false,
    },
    {
      sl: 6,
      userId: 10405,
      code: "User-1-521-001",
      userName: "User-1",
      email: "demo@gmail.com",
      ratings: 1,
      performance: 8.6,
      isActive: true,
      comment: "User-1 Comment",
      isStatusShown: true,
      status: "Written",
      isChecked: false,
    },
    {
      sl: 7,
      userId: 10406,
      code: "User-2-242-001",
      userName: "User-2",
      email: "demo@gmail.com",
      ratings: 2,
      performance: 58.8,
      isActive: false,
      comment: "User-2 Comment",
      isStatusShown: true,
      status: "Short List",
      isChecked: false,
    },
    {
      sl: 8,
      userId: 10409,
      code: "User-3-807-001",
      userName: "User-3",
      email: "demo@gmail.com",
      ratings: 3,
      performance: 88.4,
      isActive: true,
      comment: "User-3 Comment",
      isStatusShown: true,
      status: "Hire",
      isChecked: false,
    },
    {
      sl: 9,
      userId: 10410,
      code: "User-4-249-001",
      userName: "User-4",
      email: "demo@gmail.com",
      ratings: 4,
      performance: 12.3,
      status: "Reject",
      isActive: false,
      comment: "User-4 Comment",
      isStatusShown: true,
      isChecked: false,
    },
    {
      sl: 10,
      userId: 10411,
      code: "User-6-558-001",
      userName: "User-5",
      email: "demo@gmail.com",
      ratings: 5,
      performance: 45.1,
      isActive: true,
      comment: "User-5 Comment",
      isStatusShown: true,
      status: "Short List",
      isChecked: false,
    },
  ],
  pageSize: 5,
  totalCount: 10,
};
