export const LatePunishment = (workplaceDDL: any[]) => {
  return [
    {
      type: "textbox",
      label: "Punishment Policy Name",
      varname: "policyName",
      placeholder: "Enter policy name",
      rules: [
        { required: true, message: "Punishment Policy Name is required!" },
      ],
      col: 6,
    },
    {
      type: "ddl",
      label: "Workplace",
      varname: "workplace",
      ddl: workplaceDDL,
      placeholder: "Select workplace",
      rules: [{ required: true, message: "Workplace is required!" }],
      col: 6,
    },
    {
      type: "ddl",
      label: "Employment Type",
      varname: "employmentType",
      ddl: [],
      placeholder: "Select employment type",
      rules: [{ required: true, message: "Employment Type is required!" }],
      col: 6,
    },
    {
      type: "ddl",
      label: "Designation",
      varname: "designation",
      ddl: [],
      placeholder: "Select designation",
      rules: [{ required: true, message: "Designation is required!" }],
      col: 6,
    },
    {
      type: "ddl",
      label: "Department",
      varname: "department",
      ddl: [],
      placeholder: "Select department",
      rules: [{ required: true, message: "Department is required!" }],
      col: 6,
    },
    {
      type: "textbox",
      label: "Policy Description",
      varname: "policyDescription",
      placeholder: "Enter policy description",
      rules: [{ required: true, message: "Policy Description is required!" }],
      col: 6,
    },
    {
      type: "empty",
      col: 24,
    },
    {
      type: "divider",
      col: 24,
    },
    {
      type: "ddl",
      label: "Late Calculation Type",
      varname: "lateCalculationType",
      ddl: [],
      placeholder: "Select late calculation type",
      rules: [
        { required: true, message: "Late Calculation Type is required!" },
      ],
      col: 6,
    },
    {
      type: "ddl",
      label: "Each Day Count By",
      varname: "eachDayCountBy",
      ddl: [],
      placeholder: "Select each day count by",
      rules: [{ required: true, message: "Each Day Count By is required!" }],
      col: 6,
    },
    {
      type: "ddl",
      label: "Day Range",
      varname: "dayRange",
      ddl: [],
      placeholder: "Select day range",
      rules: [{ required: true, message: "Day Range is required!" }],
      col: 6,
    },
    {
      type: "checkbox",
      label: "Is Consecutive Day?",
      varname: "isConsecutiveDay",
      col: 6,
    },
    {
      type: "number",
      label: "Minimum Late Time (Minutes)",
      varname: "minimumLateTime",
      placeholder: "Enter minimum late time",
      rules: [{ required: true, message: "Minimum Late Time is required!" }],
      col: 6,
    },
    {
      type: "number",
      label: "Maximum Late Time (Minutes)",
      varname: "maximumLateTime",
      placeholder: "Enter maximum late time",
      rules: [{ required: true, message: "Maximum Late Time is required!" }],
      col: 6,
    },
    {
      type: "ddl",
      label: "Calculated By",
      varname: "calculatedBy",
      ddl: [],
      placeholder: "Select calculation type",
      rules: [{ required: true, message: "Calculated By is required!" }],
      col: 6,
    },
    {
      type: "ddl",
      label: "Punishment Type",
      varname: "punishmentType",
      ddl: [],
      placeholder: "Select punishment type",
      rules: [{ required: true, message: "Punishment Type is required!" }],
      col: 6,
    },
    {
      type: "ddl",
      label: "Leave Deduct Type",
      varname: "leaveDeductType",
      ddl: [],
      placeholder: "Select leave deduct type",
      rules: [{ required: true, message: "Leave Deduct Type is required!" }],
      col: 6,
    },
    {
      type: "number",
      label: "Leave Deduct Qty.",
      varname: "leaveDeductQty",
      placeholder: "Enter leave deduct quantity",
      rules: [{ required: true, message: "Leave Deduct Qty. is required!" }],
      col: 6,
    },
    {
      type: "ddl",
      label: "Amount Deduct From",
      varname: "amountDeductFrom",
      ddl: [],
      placeholder: "Select amount deduct from",
      rules: [{ required: true, message: "Amount Deduct From is required!" }],
      col: 6,
    },
    {
      type: "ddl",
      label: "Amount Deduct Type",
      varname: "amountDeductType",
      ddl: [],
      placeholder: "Select amount deduct type",
      rules: [{ required: true, message: "Amount Deduct Type is required!" }],
      col: 6,
    },
    {
      type: "number",
      label: "% of Amount (Based on 1 day)/ Fixed",
      varname: "amountPercentage",
      placeholder: "Enter amount percentage",
      rules: [{ required: true, message: "Amount Percentage is required!" }],
      col: 6,
    },
  ];
};
